### ISSUE TITLE
Any Issues while syncronizing files?

### ISSUE THREAD

**Issue by rodolfoleal** [Altoros/Ansible-Fabric-Starter#2]
I experienced some issues while synchronizing artifacts in task "Synchronize artifacts from orderer".

If someone also had this issues please let me know that way I can share the approach that i implemented in order to fix that.

**Comment by yod527** [comment]
Hello! Yes, rsync sometimes fails to synchronise artifacts. This is connected to network issues somehow, because you can hardly ever catch such kind of an error in local network. Maybe, rsync parameters needs to be tuned.
