### ISSUE TITLE
Fatal ERROR : Failed to connect to the host via ssh: no such identity

### ISSUE THREAD

**Issue by adarshaJha** [Altoros/Ansible-Fabric-Starter#6]
When i run this command  **ansible-playbook install-python.yml -i hosts_compact.yml**
fatal: [orderer.example.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: no such identity: /home/adarsha/test.pem: No such file or directory\r\nPermission denied (publickey,password).", "unreachable": true}

**Comment by Valansch** [comment]
The file `/home/adarsha/test.pem` does not exist. The host is refusing your connection because you failed to authenticated due to the missing identity file.

@yod527 pretty sure you wanna close this ;)
